# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf87c758116cd18301c11422212471f30af30188582bd9ff8c7ef4ba5ea2a350982e635890e2b4bcc62ce5f2eab1b4928206ae98dc3a029a53dd94a1bc88f18

test:
  secret_key_base: 044700aa05ed2398469a114fd52f4a51945bd954926c05ce9e261e705b4eda0d19934fd59a8d19a106ed249dc4bac6a77cfd1ca49198c94f7cf4f0b8235db428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
